version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.6.2

jobs:
  test-lib:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          working_directory: packages/python     
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: Run tests
          working_directory: packages/python 
          command: |
            . venv/bin/activate
            pytest
